modules:

  http-2xx-get-health:
    prober: http
    timeout: 15s
    http:
      valid_http_versions: ["HTTP/1.1", "HTTP/2"]
      valid_status_codes: [200, 400]  # Defaults to 2xx
      method: GET
      #headers:
       #Authorization: Bearer 9f6d7f6651c1ce90f9d748693ecb0a3e8cf9f057
      no_follow_redirects: false
      fail_if_ssl: false
      fail_if_not_ssl: false
      tls_config:
        insecure_skip_verify: false
      preferred_ip_protocol: "ip4" # defaults to "ip6"