scrape_configs:

  - job_name: 'exporter-test-get'
    scrape_interval: 1m
    metrics_path: /probe
    params:
      module: [http-2xx-get-health]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - grafana:3000/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: exporter-test:9115
